### ISSUE TITLE
Some praise for r-ci

### ISSUE THREAD

**Issue by erikcs** [eddelbuettel/r-ci#6]
We've been running this for 6 months on Azure - and it has performed without any hiccup whatsoever (except the rare timeout here and there from the CI provider). 

You could maybe consider highlighting this repo in a "package development/CI section" in your tinyverse guide? It actually took me a while to find this, and I would think this is a valuable alternative for people who want a no-frills R CI setup which relies mostly on Base R!

**Comment by eddelbuettel** [comment]
Paging @joshuaulrich in regards to the tinyverse page.

**Comment by eddelbuettel** [comment]
Thanks for taking the time to write the 'issue' ticket -- it is nice to hear an occassional word of encouragement. And it is nice to know that things (written to a first instance) for our own use and preference do find their use elsewhere.  So thanks.  I took the liberty to amplify this [in a tweet](https://twitter.com/eddelbuettel/status/1415122839213117446).

**Comment by erikcs** [comment]
Hi @eddelbuettel, almost 3 years later on and I have had zero problems with this CI setup. For people who want reliable R software, resources like these are invaluable.
